name: Wowza Streaming Engine Caption Handlers
services:
    wse:
        hostname: wse.docker
        image: wowza/wowza-streaming-engine:latest-trial
        platform: linux/amd64
        environment:
            - WSE_LICENSE_KEY=$WSE_LICENSE_KEY
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - IPWHITELIST=*
            - TRANSCODER=enabled #enabled | disabled | remove to not change
            - LOG_LEVEL=WARN #DEBUG INFO WARN ERROR
            - SIMU_LIVE=disabled
        volumes:
#to persist the configurations between starts of Wowza Streaming Engine, uncomment the lines below:
#            - ./wse/applications:/usr/local/WowzaStreamingEngine/applications
#            - ./wse/conf:/usr/local/WowzaStreamingEngine/conf
#            - ./wse/content:/usr/local/WowzaStreamingEngine/content
#            - ./wse/transcoder:/usr/local/WowzaStreamingEngine/transcoder
            - ./conf:/usr/local/WowzaStreamingEngine/conf.addon
            - ./build/libs:/usr/local/WowzaStreamingEngine/lib.addon
            - ./src/main/resources/transcoder:/usr/local/WowzaStreamingEngine/transcoder.addon
        ports:
            - 8087:8087
            - 80:80
            - 443:443
            - 1935:1935
            - 6970-6999:6970-6999/udp
        depends_on:
            wowza_setup:
                condition: service_completed_successfully

    wowza_setup:
        image: wowza_setup:latest
        build:
            context: wowza_setup
        restart: "no"
        volumes:
            - ./build/libs:/wowza_setup/downloads

    whisper_server:
        hostname: whisper.server
        image: wowza/whisper_streaming:latest
        #platform: linux/arm64
        environment:
            - MODEL=tiny.en # tiny.en, base.en, small.en, medium.en, large-v3
            - LOG_LEVEL=INFO
            - MIN_CHUNK_SIZE=1
            - SOURCE_LANGUAGE=en
            - REPORT_LANGUAGES=en
        ports:
            - 3000:3000
        volumes:
            - ./model_cache:/tmp

    manager:
        hostname: wsem.docker
        image: wowza/wowza-streaming-engine-manager:latest
        environment:
            - LOG_LEVEL=WARN #DEBUG INFO WARN ERROR
            - WSE_HOST=http://wse.docker:8087
        ports:
            - 8088:8080
