name: Wowza Streaming Engine Trial
services:
    trial:
        hostname: wse.docker
        image: wowza/wowza-streaming-engine:4.9.4
        env_file: .env
        environment:
            - WSE_LICENSE_KEY=$WSE_LICENSE_KEY
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - IPWHITELIST=*
            - TRANSCODER=enabled #enabled | disabled | remove to not change
            - LOG_LEVEL=INFO
            #DEBUG INFO WARN ERROR
        #to persist the configurations between starts of Wowza Streaming Engine, uncomment the lines below:
        volumes:
#            - ./wse/applications:/usr/local/WowzaStreamingEngine/applications
#            - ./wse/conf:/usr/local/WowzaStreamingEngine/conf
#            - ./wse/content:/usr/local/WowzaStreamingEngine/content
#            - ./wse/transcoder:/usr/local/WowzaStreamingEngine/transcoder
            - ./conf:/usr/local/WowzaStreamingEngine/conf.addon
            - ./build/libs:/usr/local/WowzaStreamingEngine/lib.addon
            - ./src/main/resources/transcoder:/usr/local/WowzaStreamingEngine/transcoder.addon
        ports:
            - 8087:8087
            - 80:80
            - 443:443
            - 1935:1935

    whisper_server:
        hostname: whisper.server
        image: ianzenoniwowza/wowza:whisper_streaming.poc-0.0.2
        #image: ianzenoniwowza/wowza:whisper_streaming.poc-0.0.0
        #platform: linux/arm64
        environment:
            - MODEL=tiny.en # tiny.en, base.en, small.en, medium.en, large-v3
            - LOG_LEVEL=DEBUG
            - MIN_CHUNK_SIZE=1
#            - SOURCE_STREAM=rtmp://wse.docker/live/myStream_160p
        ports:
            - 3000:3000
        volumes:
            - ./model_cache:/tmp

    manager:
        hostname: wsem.docker
        image: wowza/wowza-streaming-engine-manager:latest
        environment:
            - LOG_LEVEL=WARN #DEBUG INFO WARN ERROR
        ports:
            - 8088:8080
#        volumes:
#            - ~/Downloads:/downloads
